// Code generated by protoc-gen-go. DO NOT EDIT.
// source: keyrpc.proto

package keyrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Key struct {
	KeyName              string   `protobuf:"bytes,1,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	Virtual              uint32   `protobuf:"varint,2,opt,name=virtual,proto3" json:"virtual,omitempty"`
	Scan                 uint32   `protobuf:"varint,3,opt,name=scan,proto3" json:"scan,omitempty"`
	Sleep                int32    `protobuf:"varint,4,opt,name=sleep,proto3" json:"sleep,omitempty"`
	Mock                 bool     `protobuf:"varint,5,opt,name=mock,proto3" json:"mock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0b261c32c410cd6, []int{0}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetKeyName() string {
	if m != nil {
		return m.KeyName
	}
	return ""
}

func (m *Key) GetVirtual() uint32 {
	if m != nil {
		return m.Virtual
	}
	return 0
}

func (m *Key) GetScan() uint32 {
	if m != nil {
		return m.Scan
	}
	return 0
}

func (m *Key) GetSleep() int32 {
	if m != nil {
		return m.Sleep
	}
	return 0
}

func (m *Key) GetMock() bool {
	if m != nil {
		return m.Mock
	}
	return false
}

type EntrySummary struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntrySummary) Reset()         { *m = EntrySummary{} }
func (m *EntrySummary) String() string { return proto.CompactTextString(m) }
func (*EntrySummary) ProtoMessage()    {}
func (*EntrySummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0b261c32c410cd6, []int{1}
}

func (m *EntrySummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntrySummary.Unmarshal(m, b)
}
func (m *EntrySummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntrySummary.Marshal(b, m, deterministic)
}
func (m *EntrySummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntrySummary.Merge(m, src)
}
func (m *EntrySummary) XXX_Size() int {
	return xxx_messageInfo_EntrySummary.Size(m)
}
func (m *EntrySummary) XXX_DiscardUnknown() {
	xxx_messageInfo_EntrySummary.DiscardUnknown(m)
}

var xxx_messageInfo_EntrySummary proto.InternalMessageInfo

func (m *EntrySummary) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Key)(nil), "keyrpc.Key")
	proto.RegisterType((*EntrySummary)(nil), "keyrpc.EntrySummary")
}

func init() { proto.RegisterFile("keyrpc.proto", fileDescriptor_f0b261c32c410cd6) }

var fileDescriptor_f0b261c32c410cd6 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x8d, 0xbb, 0xed, 0xd6, 0x71, 0xbd, 0x0c, 0x7b, 0x88, 0x9e, 0x42, 0xf1, 0x90, 0xd3,
	0x82, 0x7a, 0xf4, 0x28, 0x9e, 0x0a, 0x22, 0xf1, 0x01, 0x24, 0x96, 0x39, 0x48, 0x36, 0x4d, 0x99,
	0x4d, 0xc5, 0x79, 0x7b, 0x69, 0xba, 0x0b, 0xde, 0xbe, 0x6f, 0x98, 0x99, 0x9f, 0x1f, 0xb6, 0x81,
	0x84, 0xc7, 0x7e, 0x3f, 0x72, 0xca, 0x09, 0xeb, 0xc5, 0xda, 0x5f, 0x58, 0x75, 0x24, 0x78, 0x0b,
	0x4d, 0x20, 0xf9, 0x1c, 0x7c, 0x24, 0xad, 0x8c, 0xb2, 0x57, 0x6e, 0x13, 0x48, 0xde, 0x7c, 0x24,
	0xd4, 0xb0, 0xf9, 0xf9, 0xe6, 0x3c, 0xf9, 0x83, 0xbe, 0x34, 0xca, 0xde, 0xb8, 0xb3, 0x22, 0xc2,
	0xfa, 0xd8, 0xfb, 0x41, 0xaf, 0xca, 0xb8, 0x30, 0xee, 0xa0, 0x3a, 0x1e, 0x88, 0x46, 0xbd, 0x36,
	0xca, 0x56, 0x6e, 0x91, 0x79, 0x33, 0xa6, 0x3e, 0xe8, 0xca, 0x28, 0xdb, 0xb8, 0xc2, 0xed, 0x3d,
	0x6c, 0x5f, 0x87, 0xcc, 0xf2, 0x31, 0xc5, 0xe8, 0x59, 0xe6, 0x4b, 0x62, 0x4e, 0x7c, 0xca, 0x5f,
	0xe4, 0xf1, 0x19, 0xea, 0x8e, 0xc4, 0xbd, 0xbf, 0xe0, 0x03, 0x34, 0x33, 0xa5, 0x29, 0x13, 0x5e,
	0xef, 0x4f, 0x65, 0x3a, 0x92, 0xbb, 0xdd, 0x59, 0xfe, 0xbf, 0x6b, 0x2f, 0xac, 0xfa, 0xaa, 0x4b,
	0xd7, 0xa7, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1f, 0xee, 0x0f, 0xae, 0xfb, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KeyRPCClient is the client API for KeyRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KeyRPCClient interface {
	KeyRoute(ctx context.Context, opts ...grpc.CallOption) (KeyRPC_KeyRouteClient, error)
}

type keyRPCClient struct {
	cc *grpc.ClientConn
}

func NewKeyRPCClient(cc *grpc.ClientConn) KeyRPCClient {
	return &keyRPCClient{cc}
}

func (c *keyRPCClient) KeyRoute(ctx context.Context, opts ...grpc.CallOption) (KeyRPC_KeyRouteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KeyRPC_serviceDesc.Streams[0], "/keyrpc.KeyRPC/KeyRoute", opts...)
	if err != nil {
		return nil, err
	}
	x := &keyRPCKeyRouteClient{stream}
	return x, nil
}

type KeyRPC_KeyRouteClient interface {
	Send(*Key) error
	CloseAndRecv() (*EntrySummary, error)
	grpc.ClientStream
}

type keyRPCKeyRouteClient struct {
	grpc.ClientStream
}

func (x *keyRPCKeyRouteClient) Send(m *Key) error {
	return x.ClientStream.SendMsg(m)
}

func (x *keyRPCKeyRouteClient) CloseAndRecv() (*EntrySummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(EntrySummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KeyRPCServer is the server API for KeyRPC service.
type KeyRPCServer interface {
	KeyRoute(KeyRPC_KeyRouteServer) error
}

func RegisterKeyRPCServer(s *grpc.Server, srv KeyRPCServer) {
	s.RegisterService(&_KeyRPC_serviceDesc, srv)
}

func _KeyRPC_KeyRoute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KeyRPCServer).KeyRoute(&keyRPCKeyRouteServer{stream})
}

type KeyRPC_KeyRouteServer interface {
	SendAndClose(*EntrySummary) error
	Recv() (*Key, error)
	grpc.ServerStream
}

type keyRPCKeyRouteServer struct {
	grpc.ServerStream
}

func (x *keyRPCKeyRouteServer) SendAndClose(m *EntrySummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *keyRPCKeyRouteServer) Recv() (*Key, error) {
	m := new(Key)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _KeyRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "keyrpc.KeyRPC",
	HandlerType: (*KeyRPCServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "KeyRoute",
			Handler:       _KeyRPC_KeyRoute_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "keyrpc.proto",
}
