// Code generated by protoc-gen-go. DO NOT EDIT.
// source: keyrpc.proto

package keyrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KeyPress struct {
	Key                  uint32   `protobuf:"varint,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Modifier             uint32   `protobuf:"varint,2,opt,name=Modifier,proto3" json:"Modifier,omitempty"`
	Upper                bool     `protobuf:"varint,3,opt,name=Upper,proto3" json:"Upper,omitempty"`
	Sleep                uint32   `protobuf:"varint,4,opt,name=Sleep,proto3" json:"Sleep,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyPress) Reset()         { *m = KeyPress{} }
func (m *KeyPress) String() string { return proto.CompactTextString(m) }
func (*KeyPress) ProtoMessage()    {}
func (*KeyPress) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0b261c32c410cd6, []int{0}
}

func (m *KeyPress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyPress.Unmarshal(m, b)
}
func (m *KeyPress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyPress.Marshal(b, m, deterministic)
}
func (m *KeyPress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyPress.Merge(m, src)
}
func (m *KeyPress) XXX_Size() int {
	return xxx_messageInfo_KeyPress.Size(m)
}
func (m *KeyPress) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyPress.DiscardUnknown(m)
}

var xxx_messageInfo_KeyPress proto.InternalMessageInfo

func (m *KeyPress) GetKey() uint32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *KeyPress) GetModifier() uint32 {
	if m != nil {
		return m.Modifier
	}
	return 0
}

func (m *KeyPress) GetUpper() bool {
	if m != nil {
		return m.Upper
	}
	return false
}

func (m *KeyPress) GetSleep() uint32 {
	if m != nil {
		return m.Sleep
	}
	return 0
}

type Summary struct {
	Complete             bool     `protobuf:"varint,1,opt,name=complete,proto3" json:"complete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Summary) Reset()         { *m = Summary{} }
func (m *Summary) String() string { return proto.CompactTextString(m) }
func (*Summary) ProtoMessage()    {}
func (*Summary) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0b261c32c410cd6, []int{1}
}

func (m *Summary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Summary.Unmarshal(m, b)
}
func (m *Summary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Summary.Marshal(b, m, deterministic)
}
func (m *Summary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Summary.Merge(m, src)
}
func (m *Summary) XXX_Size() int {
	return xxx_messageInfo_Summary.Size(m)
}
func (m *Summary) XXX_DiscardUnknown() {
	xxx_messageInfo_Summary.DiscardUnknown(m)
}

var xxx_messageInfo_Summary proto.InternalMessageInfo

func (m *Summary) GetComplete() bool {
	if m != nil {
		return m.Complete
	}
	return false
}

type WindowName struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WindowName) Reset()         { *m = WindowName{} }
func (m *WindowName) String() string { return proto.CompactTextString(m) }
func (*WindowName) ProtoMessage()    {}
func (*WindowName) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0b261c32c410cd6, []int{2}
}

func (m *WindowName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WindowName.Unmarshal(m, b)
}
func (m *WindowName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WindowName.Marshal(b, m, deterministic)
}
func (m *WindowName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WindowName.Merge(m, src)
}
func (m *WindowName) XXX_Size() int {
	return xxx_messageInfo_WindowName.Size(m)
}
func (m *WindowName) XXX_DiscardUnknown() {
	xxx_messageInfo_WindowName.DiscardUnknown(m)
}

var xxx_messageInfo_WindowName proto.InternalMessageInfo

func (m *WindowName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*KeyPress)(nil), "keyrpc.KeyPress")
	proto.RegisterType((*Summary)(nil), "keyrpc.Summary")
	proto.RegisterType((*WindowName)(nil), "keyrpc.WindowName")
}

func init() { proto.RegisterFile("keyrpc.proto", fileDescriptor_f0b261c32c410cd6) }

var fileDescriptor_f0b261c32c410cd6 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x8d, 0xad, 0x31, 0x0e, 0x15, 0xcb, 0xe0, 0x21, 0xf4, 0x14, 0x02, 0x42, 0x4e, 0x05,
	0x15, 0xff, 0x80, 0x1e, 0x83, 0x52, 0x36, 0x88, 0xe7, 0x9a, 0x8c, 0xb8, 0xd8, 0x75, 0x97, 0xc9,
	0x96, 0xb2, 0xff, 0x5e, 0x32, 0xdb, 0xc4, 0x4b, 0x4f, 0x3b, 0xdf, 0xe3, 0xed, 0xbe, 0x7d, 0x03,
	0x8b, 0x1f, 0x0a, 0xec, 0xda, 0xb5, 0x63, 0xeb, 0x2d, 0xa6, 0x91, 0xca, 0x0e, 0xb2, 0x9a, 0xc2,
	0x86, 0xa9, 0xef, 0x71, 0x09, 0xb3, 0x9a, 0x42, 0x9e, 0x14, 0x49, 0x75, 0xad, 0x86, 0x11, 0x57,
	0x90, 0xbd, 0xda, 0x4e, 0x7f, 0x69, 0xe2, 0xfc, 0x5c, 0xe4, 0x89, 0xf1, 0x16, 0x2e, 0xde, 0x9d,
	0x23, 0xce, 0x67, 0x45, 0x52, 0x65, 0x2a, 0xc2, 0xa0, 0x36, 0x3b, 0x22, 0x97, 0xcf, 0xc5, 0x1e,
	0xa1, 0xbc, 0x83, 0xcb, 0x66, 0x6f, 0xcc, 0x96, 0xe5, 0xc9, 0xd6, 0x1a, 0xb7, 0x23, 0x4f, 0x92,
	0x94, 0xa9, 0x89, 0xcb, 0x02, 0xe0, 0x43, 0xff, 0x76, 0xf6, 0xf0, 0xb6, 0x35, 0x84, 0x08, 0xf3,
	0xe1, 0x14, 0xd7, 0x95, 0x92, 0xf9, 0x81, 0x21, 0xad, 0x29, 0xa8, 0xcd, 0x0b, 0xde, 0xcb, 0xc7,
	0x9f, 0xf7, 0xdc, 0x7b, 0x5c, 0xae, 0x8f, 0xdd, 0xc6, 0x2a, 0xab, 0x9b, 0x51, 0x39, 0xc6, 0x96,
	0x67, 0x55, 0x82, 0x4f, 0xb0, 0x68, 0x0e, 0xda, 0xb7, 0xdf, 0x31, 0x04, 0x71, 0x34, 0xfd, 0x87,
	0x9e, 0xb8, 0xf8, 0x99, 0xca, 0xc6, 0x1e, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x1a, 0x49,
	0x26, 0x41, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KeyRPCClient is the client API for KeyRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KeyRPCClient interface {
	KeyBurst(ctx context.Context, opts ...grpc.CallOption) (KeyRPC_KeyBurstClient, error)
	SwitchWindow(ctx context.Context, in *WindowName, opts ...grpc.CallOption) (*Summary, error)
}

type keyRPCClient struct {
	cc *grpc.ClientConn
}

func NewKeyRPCClient(cc *grpc.ClientConn) KeyRPCClient {
	return &keyRPCClient{cc}
}

func (c *keyRPCClient) KeyBurst(ctx context.Context, opts ...grpc.CallOption) (KeyRPC_KeyBurstClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KeyRPC_serviceDesc.Streams[0], "/keyrpc.KeyRPC/KeyBurst", opts...)
	if err != nil {
		return nil, err
	}
	x := &keyRPCKeyBurstClient{stream}
	return x, nil
}

type KeyRPC_KeyBurstClient interface {
	Send(*KeyPress) error
	CloseAndRecv() (*Summary, error)
	grpc.ClientStream
}

type keyRPCKeyBurstClient struct {
	grpc.ClientStream
}

func (x *keyRPCKeyBurstClient) Send(m *KeyPress) error {
	return x.ClientStream.SendMsg(m)
}

func (x *keyRPCKeyBurstClient) CloseAndRecv() (*Summary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Summary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *keyRPCClient) SwitchWindow(ctx context.Context, in *WindowName, opts ...grpc.CallOption) (*Summary, error) {
	out := new(Summary)
	err := c.cc.Invoke(ctx, "/keyrpc.KeyRPC/SwitchWindow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyRPCServer is the server API for KeyRPC service.
type KeyRPCServer interface {
	KeyBurst(KeyRPC_KeyBurstServer) error
	SwitchWindow(context.Context, *WindowName) (*Summary, error)
}

func RegisterKeyRPCServer(s *grpc.Server, srv KeyRPCServer) {
	s.RegisterService(&_KeyRPC_serviceDesc, srv)
}

func _KeyRPC_KeyBurst_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KeyRPCServer).KeyBurst(&keyRPCKeyBurstServer{stream})
}

type KeyRPC_KeyBurstServer interface {
	SendAndClose(*Summary) error
	Recv() (*KeyPress, error)
	grpc.ServerStream
}

type keyRPCKeyBurstServer struct {
	grpc.ServerStream
}

func (x *keyRPCKeyBurstServer) SendAndClose(m *Summary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *keyRPCKeyBurstServer) Recv() (*KeyPress, error) {
	m := new(KeyPress)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _KeyRPC_SwitchWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WindowName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyRPCServer).SwitchWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keyrpc.KeyRPC/SwitchWindow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyRPCServer).SwitchWindow(ctx, req.(*WindowName))
	}
	return interceptor(ctx, in, info, handler)
}

var _KeyRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "keyrpc.KeyRPC",
	HandlerType: (*KeyRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SwitchWindow",
			Handler:    _KeyRPC_SwitchWindow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "KeyBurst",
			Handler:       _KeyRPC_KeyBurst_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "keyrpc.proto",
}
