// Code generated by protoc-gen-go. DO NOT EDIT.
// source: keyrpc.proto

package keyrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KeyPress struct {
	Key                  uint32   `protobuf:"varint,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Modifier             uint32   `protobuf:"varint,2,opt,name=Modifier,proto3" json:"Modifier,omitempty"`
	Upper                bool     `protobuf:"varint,3,opt,name=Upper,proto3" json:"Upper,omitempty"`
	Sleep                uint32   `protobuf:"varint,4,opt,name=Sleep,proto3" json:"Sleep,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyPress) Reset()         { *m = KeyPress{} }
func (m *KeyPress) String() string { return proto.CompactTextString(m) }
func (*KeyPress) ProtoMessage()    {}
func (*KeyPress) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0b261c32c410cd6, []int{0}
}

func (m *KeyPress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyPress.Unmarshal(m, b)
}
func (m *KeyPress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyPress.Marshal(b, m, deterministic)
}
func (m *KeyPress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyPress.Merge(m, src)
}
func (m *KeyPress) XXX_Size() int {
	return xxx_messageInfo_KeyPress.Size(m)
}
func (m *KeyPress) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyPress.DiscardUnknown(m)
}

var xxx_messageInfo_KeyPress proto.InternalMessageInfo

func (m *KeyPress) GetKey() uint32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *KeyPress) GetModifier() uint32 {
	if m != nil {
		return m.Modifier
	}
	return 0
}

func (m *KeyPress) GetUpper() bool {
	if m != nil {
		return m.Upper
	}
	return false
}

func (m *KeyPress) GetSleep() uint32 {
	if m != nil {
		return m.Sleep
	}
	return 0
}

type Summary struct {
	Complete             bool     `protobuf:"varint,1,opt,name=complete,proto3" json:"complete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Summary) Reset()         { *m = Summary{} }
func (m *Summary) String() string { return proto.CompactTextString(m) }
func (*Summary) ProtoMessage()    {}
func (*Summary) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0b261c32c410cd6, []int{1}
}

func (m *Summary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Summary.Unmarshal(m, b)
}
func (m *Summary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Summary.Marshal(b, m, deterministic)
}
func (m *Summary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Summary.Merge(m, src)
}
func (m *Summary) XXX_Size() int {
	return xxx_messageInfo_Summary.Size(m)
}
func (m *Summary) XXX_DiscardUnknown() {
	xxx_messageInfo_Summary.DiscardUnknown(m)
}

var xxx_messageInfo_Summary proto.InternalMessageInfo

func (m *Summary) GetComplete() bool {
	if m != nil {
		return m.Complete
	}
	return false
}

func init() {
	proto.RegisterType((*KeyPress)(nil), "keyrpc.KeyPress")
	proto.RegisterType((*Summary)(nil), "keyrpc.Summary")
}

func init() { proto.RegisterFile("keyrpc.proto", fileDescriptor_f0b261c32c410cd6) }

var fileDescriptor_f0b261c32c410cd6 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x4e, 0xad, 0x2c,
	0x2a, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x52, 0xb8, 0x38,
	0xbc, 0x53, 0x2b, 0x03, 0x8a, 0x52, 0x8b, 0x8b, 0x85, 0x04, 0xb8, 0x98, 0xbd, 0x53, 0x2b, 0x25,
	0x18, 0x15, 0x18, 0x35, 0x78, 0x83, 0x40, 0x4c, 0x21, 0x29, 0x2e, 0x0e, 0xdf, 0xfc, 0x94, 0xcc,
	0xb4, 0xcc, 0xd4, 0x22, 0x09, 0x26, 0xb0, 0x30, 0x9c, 0x2f, 0x24, 0xc2, 0xc5, 0x1a, 0x5a, 0x50,
	0x90, 0x5a, 0x24, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x11, 0x04, 0xe1, 0x80, 0x44, 0x83, 0x73, 0x52,
	0x53, 0x0b, 0x24, 0x58, 0xc0, 0xca, 0x21, 0x1c, 0x25, 0x55, 0x2e, 0xf6, 0xe0, 0xd2, 0xdc, 0xdc,
	0xc4, 0x22, 0xb0, 0x91, 0xc9, 0xf9, 0xb9, 0x05, 0x39, 0xa9, 0x25, 0xa9, 0x60, 0x9b, 0x38, 0x82,
	0xe0, 0x7c, 0x23, 0x6b, 0x2e, 0x36, 0xef, 0xd4, 0xca, 0xa0, 0x00, 0x67, 0x21, 0x43, 0xb0, 0xb3,
	0x9c, 0x4a, 0x8b, 0x8a, 0x4b, 0x84, 0x04, 0xf4, 0xa0, 0x2e, 0x87, 0x39, 0x54, 0x8a, 0x1f, 0x26,
	0x02, 0x35, 0x54, 0x89, 0x41, 0x83, 0x31, 0x89, 0x0d, 0xec, 0x31, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xed, 0x06, 0x81, 0xc3, 0xe8, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KeyRPCClient is the client API for KeyRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KeyRPCClient interface {
	KeyBurst(ctx context.Context, opts ...grpc.CallOption) (KeyRPC_KeyBurstClient, error)
}

type keyRPCClient struct {
	cc *grpc.ClientConn
}

func NewKeyRPCClient(cc *grpc.ClientConn) KeyRPCClient {
	return &keyRPCClient{cc}
}

func (c *keyRPCClient) KeyBurst(ctx context.Context, opts ...grpc.CallOption) (KeyRPC_KeyBurstClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KeyRPC_serviceDesc.Streams[0], "/keyrpc.KeyRPC/KeyBurst", opts...)
	if err != nil {
		return nil, err
	}
	x := &keyRPCKeyBurstClient{stream}
	return x, nil
}

type KeyRPC_KeyBurstClient interface {
	Send(*KeyPress) error
	CloseAndRecv() (*Summary, error)
	grpc.ClientStream
}

type keyRPCKeyBurstClient struct {
	grpc.ClientStream
}

func (x *keyRPCKeyBurstClient) Send(m *KeyPress) error {
	return x.ClientStream.SendMsg(m)
}

func (x *keyRPCKeyBurstClient) CloseAndRecv() (*Summary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Summary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KeyRPCServer is the server API for KeyRPC service.
type KeyRPCServer interface {
	KeyBurst(KeyRPC_KeyBurstServer) error
}

func RegisterKeyRPCServer(s *grpc.Server, srv KeyRPCServer) {
	s.RegisterService(&_KeyRPC_serviceDesc, srv)
}

func _KeyRPC_KeyBurst_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KeyRPCServer).KeyBurst(&keyRPCKeyBurstServer{stream})
}

type KeyRPC_KeyBurstServer interface {
	SendAndClose(*Summary) error
	Recv() (*KeyPress, error)
	grpc.ServerStream
}

type keyRPCKeyBurstServer struct {
	grpc.ServerStream
}

func (x *keyRPCKeyBurstServer) SendAndClose(m *Summary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *keyRPCKeyBurstServer) Recv() (*KeyPress, error) {
	m := new(KeyPress)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _KeyRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "keyrpc.KeyRPC",
	HandlerType: (*KeyRPCServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "KeyBurst",
			Handler:       _KeyRPC_KeyBurst_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "keyrpc.proto",
}
